### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by easella** [Flying-Toast/wiziz#115]
can you please deploy it to heroku? I really want to play the game but my school blocks it and with all the proxy server I have tried I am disconnected from the server. Please deploy it to heroku.

**Comment by Flying-Toast** [comment]
The reason you are seeing a server disconnected message on your "proxy server" is because the client tries to open a websocket connection to the `ws` subdomain of the site's hostname to connect to the game server. Since I assume your proxy is just serving the static files from wiziz.io, this won't work. I'm not going to change this behavior though because I don't want people embedding wiziz.io on their "io games unblocked proxy site" so they can steal my bandwidth and plaster the site with their own ads (by the way, I can see that you are trying to do just this judging by your public repositories :P). If you would like wiziz on your site, feel free to host your own server -- it's all AGPL licensed. But please don't embed my own instance.
